amcl:
  ros__parameters:
    # params to modify
    min_particles: 500 # Minimum allowed number of particles.
    max_particles: 3000 # Maximum allowed number of particles.
    update_min_d: 0.05 # Translational movement required before performing a filter update.
    update_min_a: 0.05 # Rotational movement required before performing a filter update.
    resample_interval: 1 # Number of filter updates required before resampling.
    laser_min_range: -1.0 # Minimum scan range to be considered; -1.0 will cause the laser's reported minimum range to be used.
    laser_max_range: 3.5 # Maximum scan range to be considered; -1.0 will cause the laser's reported maximum range to be used.
    laser_max_beams: 180 # How many evenly-spaced beams in each scan to be used when updating the filter.
    odom_model_type: "diff" # Which model to use, either "diff", "omni", "diff-corrected" or "omni-corrected".

    # ==========================
    set_initial_pose: True

    scan_topic: "scan"

    ###########################

    kld_err: 0.02

    transform_tolerance: 0.5
    recovery_alpha_slow: 0.00
    recovery_alpha_fast: 0.00

    gui_publish_rate: 50.0

    laser_z_hit: 0.5
    laser_z_short: 0.05
    laser_z_max: 0.05
    laser_z_rand: 0.5
    laser_sigma_hit: 0.2
    laser_lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_model_type: "likelihood_field"

    odom_alpha1: 0.4
    odom_alpha2: 0.4
    odom_alpha3: 0.4
    odom_alpha4: 0.4
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
