turtlebot3_slam_gmapping:
  ros__parameters:
    # params to modify
    delta: 0.025 # Resolution of the map (in metres per occupancy grid block)
    maxUrange: 3.0 # The maximum usable range of the laser. A beam is cropped to this value.
    linearUpdate: 0.05 # Process a scan each time the robot translates this far
    angularUpdate: 0.05 # Process a scan each time the robot rotates this far
    map_update_interval: 1.0 # How long (in seconds) between updates to the map. Lowering this number updates the occupancy grid more often, at the expense of greater computational load.

    ############

    sigma: 0.05
    kernelSize: 1
    lstep: 0.05
    astep: 0.05
    iterations: 5
    lsigma: 0.075
    ogain: 3.0
    lskip: 0
    minimumScore: 50.0
    srr: 0.1
    srt: 0.2
    str: 0.1
    stt: 0.2
    temporalUpdate: 0.5
    resampleThreshold: 0.5
    particles: 100
    xmin: -10.0
    ymin: -10.0
    xmax: 10.0
    ymax: 10.0
    llsamplerange: 0.01
    llsamplestep: 0.01
    lasamplerange: 0.005
    lasamplestep: 0.005
