navigator_node:
  ros__parameters:
    robot_radius: 0.19 # radius considered of the robot to check collisions with environment.
    goal_tolerance: 0.2 # error tolerated by the finish point of the path to the goal
    use_path_smoother: False # if it is desired to make the path smooth
    max_planning_bounds: [20, 20]


    map_topic: /projected_map
